function LLSUMMONINF_Ext_SummonTemplateAtPosition(player, template, xs, ys, zs, lifetimestr, totemstr)
	local x = tonumber(xs)
	local y = tonumber(ys)
	local z = tonumber(zs)
	local lifetime = tonumber(lifetimestr)
	local totem = tonumber(totemstr)
	local level = CharacterGetLevel(player)
	--Ext.Print("NRD_Summon: "..player, template, x, y, z, lifetime, level, totem)
	local summon = NRD_Summon(player, template, x, y, z, lifetime, level, totem, 1)
	--local summon = NRD_Summon("S_GLO_CharacterCreationDummy_001_da072fe7-fdd5-42ae-9139-8bd4b9fca406", "13f9314d-e744-4dc5-acf2-c6bf77a04892", 0, 0, 0, 60.0, 10, 0, 1)
	--local last_underscore = string.find(template, "_[^_]*$")
	--local stripped_template = string.sub(template, last_underscore+1)
	--Osi.LLSUMMONINF_SummonTemplateAtPosition_Go(player, stripped_template, x, y, z, lifetime, totem)
	--PlayEffectAtPosition("RS3_FX_UI_Icon_SkipTurn_UsedScroll_01", x, y + 2.0, z)
	PlayEffect(summon, "RS3_FX_UI_Icon_SkipTurn_UsedScroll_01", "Dummy_OverheadFX")
	PlayEffectAtPosition("LLSUMMONINF_Skills_InvokeContract_Cast_Summon_01", x, y, z)
	PlayEffectAtPosition("RS3_FX_Skills_Totem_Target_Nebula_01", x, y, z)
end